[tool.poetry]
name = "backend"
version = "0.1.0"
description = ""
authors = ["Davi Sousa <davi.gomes.sousa@ccc.ufcg.edu.br>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.103.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
